version: '2.4'

services:

  # master:
  #   image: ros:noetic-ros-core
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - ROS_MASTER_URI=http://127.0.0.1:11311
  #     - ROS_IP=127.0.0.1
  #   command: roscore

  # camera:
  #   image: realsense
  #   privileged: true
  #   build:
  #     context: . 
  #     dockerfile: dockerfile
  #   network_mode: "host"
  #   runtime: "nvidia"
  #   volumes:
  #     - /dev/bus/usb:/dev/bus/usb
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   environment:
  #     - ROS_MASTER_URI=http://127.0.0.1:11311
  #     - ROS_IP=127.0.0.1
  #     - DISPLAY
  #     - QT_X11_NO_MITSHM=1
  #   command: bash -c "source catkin_ws/devel/setup.bash; roslaunch --wait realsense2_camera rs_camera.launch"
  #   stdin_open: true
  #   tty: true 

  yolo:
    image: yolo_ros_ycbv
    privileged: true
    build:
      context: .
      dockerfile: dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/iChores/yolov5:/root/yolo
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source catkin_ws/devel/setup.bash; python ./yolo/detect_ros_seg.py --weights ./yolo/runs/train-seg/exp14/weights/last.pt --data ./yolo/data/ycbv.yaml --conf-thres 0.9 --iou-thres 0.7 --camera-topic /camera/color/image_raw"
    stdin_open: true
    tty: true 