version: '2.4'

services:

  yolo_seg_service:
    image: yolo_seg_service
    privileged: true
    build:
      context: .
      dockerfile: dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/iChores/yolov5:/root/yolo
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source /opt/ros/noetic/setup.bash; source catkin_ws/devel/setup.bash; python ./yolo/yolov5_det_service.py"
    stdin_open: true
    tty: true 